version: '3.7'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  fastapi:
    build:
      context: https://github.com/EventGamer67/Medusa.git#master
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
  telegram_bot:
    build:
      context: https://github.com/EventGamer67/Uksivt_telegram.git#master
      dockerfile: Dockerfile
