version: '3.7'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - medusa_network

  fastapi:
    build:
      context: https://github.com/EventGamer67/Medusa.git#master
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - medusa_network

  telegram_bot:
    build:
      context: https://github.com/EventGamer67/Uksivt_telegram.git#master
      dockerfile: Dockerfile
    networks:
      - medusa_network

networks:
  medusa_network:
    driver: bridge
